Vector or 1D Array

In [152]:
list = [1, 2, 3]

In [153]:
list

[1, 2, 3]

In [154]:
import numpy as np

In [155]:
arr = np.array(list)

In [156]:
arr

array([1, 2, 3])

Matrix or 2D Array

In [157]:
mat = [[1,2,3], [4,5,6],[7,8,9]]

In [158]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arange()

In [159]:
np.arange(0,10)

# arange is similar to range function which is built in in Python. 
# This will include all the numbers from 0 to before 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
np.arange(0, 11, 2) # the third parameter is the increment.

array([ 0,  2,  4,  6,  8, 10])

np.zeros()

In [161]:
np.zeros(3) # generating arrays of zeroes

array([0., 0., 0.])

In [162]:
np.zeros((5,5)) # this will create a 2D array of zeroes of tuple value 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones()

In [163]:
np.ones(4)  # generating arrays of ones

array([1., 1., 1., 1.])

In [164]:
np.ones((3,4)) # this will create a 2D array of ones of tuple value 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.linspace()

In [165]:
np.linspace(0,5,10) # this will create an array from 0 to 5 with 10 evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

np.eye()

In [166]:
np.eye(4) # this function is helpful in finding identity matrix, its helpful in linear algebra problems.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random() and its sub functions

In [167]:
np.random.rand(5) # this will create an array of random numbers from 0 to 1.
# In bracket we have to specify the number of elements that will be stored inside the array.

array([0.45211568, 0.85310049, 0.36884779, 0.94450508, 0.80158942])

In [168]:
np.random.rand(5,5) # this will create a 2D array of random numbers from 0 to 1.
# In bracket we have to specify the number of rows and columns for the array.

array([[0.6755642 , 0.48924984, 0.29972617, 0.53385687, 0.75856016],
       [0.22079614, 0.18734449, 0.97997473, 0.70706239, 0.76378991],
       [0.36350497, 0.9214787 , 0.91377689, 0.52294345, 0.4275056 ],
       [0.78357506, 0.29232969, 0.85561262, 0.22501104, 0.45881965],
       [0.25676504, 0.58881706, 0.57553769, 0.5962911 , 0.95762073]])

In [169]:
np.random.randn(2)  # this will create an array of random Gaussian or standard normal distribution center from 0 to 1.
# In bracket we have to specify the number of elements that will be stored inside the array.

array([-0.00284265,  1.137773  ])

In [170]:
np.random.randn(4,4) # this will create a 2D array of random Gaussian or standard normal distribution center from 0 to 1.
# In bracket we have to specify the number of rows and columns for the array.

array([[ 0.29633696,  0.90773505,  0.20038381,  0.48215359],
       [-1.15802433,  0.61751475, -0.28473304, -1.22320538],
       [-0.99409632, -0.39350488, -0.92702361, -0.9044186 ],
       [-0.53752384, -0.70396722, -0.45870063, -0.70684161]])

In [171]:
np.random.randint(1,100,10) # this will give an array integer from 1 to 100. 
# Here 10 is the number of elements we want to store in our array.
# Here 1 is inclusive but 100 is exclusive, i.e. 1 may come as a random outcome but 100 will never come.

array([10, 38,  1, 65, 16, 12, 61, 50, 51, 98])

np.reshape()

In [172]:
arr = np.arange(25)

In [173]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [174]:
arr.reshape(5,5)  # this will re-create a 2D array of the np.arange fucntion. 
# But we have to stick with the number of elements in the np.arange, we cant change it in reshape.
# Like in top in np.arange we had 25 number of elements.
# so for reshape function we can't change it to anything else but 5 * 5 for holding 25 number of elements.
# Specifying anything other than that will show error.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

np.max() / np.min() and its sub functions

In [175]:
arr.max() # this will give the maximum element in the array

24

In [176]:
arr.min() # this will give the minimum element in the array

0

In [177]:
arr.argmax() # this will return the index location of the max value

24

In [178]:
arr.argmin()  # this will return the index location of the min value

0

In [179]:
arr.shape # this will return the diment=sion or type of array one array is
# in this case, this array is one dimensional with 25 elements, hence there is one value returning

(25,)

In [180]:
arr = arr.reshape(5,5) # if we reshape it, then:

In [181]:
arr.shape # this will return the dimensions again, which is now in this 2D

(5, 5)

In [182]:
arr.dtype # this will return the data type of elements inside the array.
# in this case its 32 bit integers.

dtype('int32')

# Shortcut for getting rid of np all time

In [183]:
# for example we want to run np.random.randint(), but its too much to write np all the time.
# for that we can:

In [184]:
from numpy.random import randint

In [185]:
randint(2, 10) # this will return a random integer from including 2 to excluding 10.

3

## Numpy Indexing and Selection

In [186]:
arr = np.arange(0,11)

In [187]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [188]:
arr[8] # index of value 8 which is 8

8

In [189]:
arr[1:5] # slicing of array from 1 to 5.
# 1 with index 0 to 4 as index 3

array([1, 2, 3, 4])

In [190]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [191]:
arr[:6] # this will return everything  from start to index 6

array([0, 1, 2, 3, 4, 5])

In [192]:
arr[5:] # this will return everything from 5 onwards to the end of the array

array([ 5,  6,  7,  8,  9, 10])

In [193]:
arr[0:5] = 100 # this will broadcast 100 as the element from index 0 to before 5

In [194]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [195]:
slice_of_arr = arr[0:6] # this will return everything from 0 to before 6 index

In [196]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [197]:
arr = np.arange(0,11)

In [198]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [199]:
slice_of_arr = arr[0:6]

In [200]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [201]:
slice_of_arr[:] # [:] means grabbing everything in one array

array([0, 1, 2, 3, 4, 5])

In [202]:
slice_of_arr[:] = 99  # this will broadcast 99 as the element for the entire array

In [203]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [204]:
arr # this change of 99 occuring in the original array too.
# because the data is not copied and its just a view of the original array.
# NumPy does this to avoid memory issues with very large arrays.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [205]:
arr_copy = arr.copy() # this function will create a copy of our data 

In [206]:
arr # for now original array and

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [207]:
arr_copy # copied array are same

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [208]:
arr_copy[:] = 100 # we can make changes to the copied arr

In [209]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [210]:
arr # so now the original array is unaffected and we can make changes to the copied array however we want to

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing, Slicing Selection on 2D Arrays

In [211]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [212]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [213]:
arr_2d[0][0] # for grabbing an element in 2D array:
# we have to first specify the index of specific array then the index of its element
# this is called 'double bracket notation'.

5

In [214]:
# we can also use 'single bracket notation' to grab elements from a 2D array
arr_2d[0,0]

5

What if we want to grab some from one matrix then another from some another matrix

In [215]:
arr_2d[:2,1:] # this means grabbing everything upto row 1 , and then grabbing from column 0

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [216]:
arr = np.arange(1, 11)

In [217]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
bool_arr = arr > 5  # this will check with every elements of the array if 5 is greater than them or not,
# and will return boolean values.

In [219]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [220]:
arr[bool_arr] # this will return the array with only True Values and will remove False ones

array([ 6,  7,  8,  9, 10])

In [221]:
arr[arr>5] # this will also return the same. It is the shortcut for the above

array([ 6,  7,  8,  9, 10])

In [222]:
arr_2d = np.arange(50).reshape(5,10)

Problem Statement Based on Indexing and Selection:

In [223]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Suppose we want 13,14 and 23,24, we have to:

In [224]:
arr_2d[1:3,3:5] # this will return rows from 1 o before 3, i.e 1,2 
# and this will return column 3 to before 5 based on rows mentioned before.

array([[13, 14],
       [23, 24]])