For more detailed Universal Numpy Fucntions visit: https://numpy.org/devdocs/reference/ufuncs.html

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Basic Arithmetic Operations

Adding Arrays 

In [4]:
arr + arr # basically this is how we add two arrays together
# here array is getting added by itself hence the output is:

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr + 100 # this will add 100 to each element of the array and show the resulting array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

same can be done with subtraction/multiplication/division etc.

In [7]:
# 0/0  or anything divided by 0 gives ZeroDivisiononError'.
# but in Numpy it will give a warning but we will get a resulting output:

In [8]:
arr / arr # this is showing nan

C:\Users\roysu\AppData\Local\Temp\ipykernel_25412\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
1 /  arr # this will show infinte for 0

C:\Users\roysu\AppData\Local\Temp\ipykernel_25412\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

To find the Square Root of every element in an array:

In [14]:
np.sqrt(arr) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

To find the Exponential of every element in an array:

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

To find the maximum element in an array:

In [16]:
np.max(arr)
# or
# arr.max()

10

To find the Trigonometric Functions like sin of every element in an array:

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

To find the Log of every element in an array:

In [18]:
np.log(arr) # this will give negative infinte for 0

C:\Users\roysu\AppData\Local\Temp\ipykernel_25412\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

To find the sum of every element in an array:

In [19]:
np.sum(arr)

55

To find Sum of every element over row/column:

In [34]:
mat = np.arange(0,21).reshape(3,7)
mat

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [35]:
mat.sum(axis=0) # this will give the sum of elements over the column that is vertically sum of all the columns.

array([21, 24, 27, 30, 33, 36, 39])

In [36]:
mat.sum(axis=1) # this will give the sum of elements over the row that is horizontal sum of all the rows.

array([ 21,  70, 119])

To find the standard deviation of every element in an array:

In [37]:
np.std(arr)

3.1622776601683795